---
- name: "first play boss"
  hosts: servers
  become: yes
  tasks:
    - name: "to install tree"
      apt:
        name: tree
        state: present
    - name: "to install ifconfig"
      apt:
        name: net-tools
        state: present
